[project]
name = "dietitian"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.43.25",
    "cos-python-sdk-v5>=1.9.43",
    "fastapi>=0.128.8",
    "langchain>=0.3.30",
    "langchain-openai>=0.3.35",
    "langchain-tavily>=0.2.11",
    "langgraph>=0.6.11",
    "langgraph-checkpoint-mongodb>=0.2.1",
    "pydantic>=2.13.4",
    "python-dotenv",
    "uvicorn>=0.39.0",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
